In [1]:
import numpy as np

# Slicing of a 2-D array

In [5]:
# arr[row_slicing]
# arr[start:stop:step]

# arr[row_slicing, col_slicing]
# arr[start:stop:step,start:stop:step]

In [4]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
# Fetch the first two rows

arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# Fetch the first and the last rows only

arr[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [8]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# Reverse the rows

arr[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [10]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# Get the first column

arr[::,0]

array([1, 5, 9])

In [15]:
arr[::,[0]]

array([[1],
       [5],
       [9]])

In [16]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# Get the first two columns

arr[::,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
# Reverse the columns

arr[::,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [23]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
# Fetch the upper right to lower left diagonal

# [5,9,13,17,21]

np.diagonal(arr[::,::-1])

array([ 5,  9, 13, 17, 21])

In [29]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
# Lower left to upper right diagonal elements

# [21,17,13,9,5]

np.diagonal(arr[::,::-1])[::-1]

array([21, 17, 13,  9,  5])

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
# Fetch [[1,4],
#       [11,14]]

arr[0:3:2,::3]

array([[ 1,  4],
       [11, 14]])

In [38]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
# Fetch the corner elemnts

# [[1,5],
# [21,25]]

arr[::4,::4]

array([[ 1,  5],
       [21, 25]])

In [43]:
# [[25,21],
#  [5,1]]

arr[::-4,::-4]

array([[25, 21],
       [ 5,  1]])

# Indexing and slicing of a 3-D array

# Indexing

In [46]:
# arr[array_index]

# arr[array_index,row_index]

# arr[array_index,row_index,col_index]

In [45]:
arr=np.arange(1,37).reshape(4,3,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [47]:
len(arr)

4

In [48]:
# Fetch the first array

arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr[-4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
-len(arr)

-4

In [52]:
arr[-len(arr)]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# Fetch the last array

arr[-1]

array([[28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [54]:
arr[3]

array([[28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [56]:
len(arr)-1

3

In [57]:
arr[len(arr)-1]

array([[28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [58]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [60]:
# Fetch the first row from the first array

arr[0,0]

array([1, 2, 3])

In [62]:
# Last row from the second array
arr[1,-1]

array([16, 17, 18])

In [65]:
# Fetch 20

arr[-2,0,1]

20

# Slicing

In [66]:
# arr[array_slicing]
# arr[start:stop:step]

# arr[array_slicing,row_slicing]
# arr[start:stop:step,start:stop:step]

# arr[array_slicing,row_slicing,col_slicing]
# arr[start:stop:step,start:stop:step,start:stop:step]

In [67]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [68]:
# Fetch the first two arrays

arr[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [69]:
# Reverse the arrays

arr[::-1]

array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [73]:
# Fetch the first two rows from the first two arrays

arr[0:2,0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [75]:
# Reverse the rows in each array

arr[::,::-1]

array([[[ 7,  8,  9],
        [ 4,  5,  6],
        [ 1,  2,  3]],

       [[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]],

       [[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]]])

In [78]:
# First two columns from all the arrays

arr[::,::,0:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]],

       [[28, 29],
        [31, 32],
        [34, 35]]])

# Functions on arrays

In [98]:
# np.sum()
# np.max()
# np.min()
# np.argmax()
# np.argmin()
# np.mean()
# np.median()
# np.var()
# np.std()
# np.percentile()
# np.where()
# np.select()
# np.clip()
# np.isnan()

# np.sum()
- It returns the sum of all the elements of the array

In [86]:
# np.sum(arr,axis=0/1)
# arr.sum(axis=0/1)

In [91]:
# axis=0- It is known as row wise operation (Top to bottom operation)
# axis=1- Column wise operation (Left to right operation)

In [83]:
arr=np.array([[2,4,6,8],[7,8,9,5],[4,6,9,6]])
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [84]:
np.sum(arr)

74

In [85]:
arr.sum()

74

In [90]:
arr.sum(axis=0)

array([13, 18, 24, 19])

In [89]:
arr.sum(axis=1)

array([20, 29, 25])

In [92]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [94]:
np.sum(arr,axis=0)

array([13, 18, 24, 19])

# np.max()
- It returns the maximum of an array

In [97]:
# np.max(arr,axis=0/1)
# arr.max(axis=0/1)

In [95]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [96]:
np.max(arr)

9

In [99]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [107]:
np.max(arr,axis=0)

array([7, 8, 9, 8])

In [109]:
np.max(arr,axis=1)

array([8, 9, 9])

In [106]:
# arr[::,0:2].sum()

# np.min()
- It returns the minimum of an array

In [110]:
# np.min(arr,axis=0/1)
# arr.min(axis=0/1)

In [111]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [112]:
np.min(arr)

2

In [113]:
np.min(arr,axis=0)

array([2, 4, 6, 5])

In [114]:
np.min(arr,axis=1)

array([2, 5, 4])

# np.argmax()

- It returns the index of the first occurence of the maximum number.
- It considers an n-D array as a 1-D array

In [116]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [117]:
np.argmax(arr)

6

In [118]:
arr.ravel()

array([2, 4, 6, 8, 7, 8, 9, 5, 4, 6, 9, 6])

# np.argmin()
- It returns the index of the first occurence of the minimum number.
- It considers an n-D array as a 1-D array

In [119]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [120]:
np.argmin(arr)

0

# np.mean()
- It returns the mean (average) of the array

In [122]:
# np.mean(arr,axis=0/1)
# arr.mean(axis=0/1)

In [123]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [124]:
arr.mean()

6.166666666666667

In [128]:
arr.sum()/arr.size

6.166666666666667

In [129]:
len(arr)

3

In [130]:
arr.size

12

In [131]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [132]:
arr.mean(axis=0)

array([4.33333333, 6.        , 8.        , 6.33333333])

In [133]:
arr.mean(axis=1)

array([5.  , 7.25, 6.25])

# np.median()
- It returns the median of an array

In [134]:
# np.median(arr,axis=0/1)

In [135]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [136]:
np.median(arr)

6.0

In [137]:
np.median(arr,axis=0)

array([4., 6., 9., 6.])

In [139]:
np.median(arr,axis=1)

array([5. , 7.5, 6. ])

In [141]:
# arr.median()

In [142]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [143]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

# np.std()
- It returns the standard deviation of an array.

In [144]:
# np.std(arr,axis=0/1)
# arr.std(axis=0/1)

In [145]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [146]:
np.std(arr)

2.0749832663314556

In [148]:
np.std(arr,axis=0)

array([2.05480467, 1.63299316, 1.41421356, 1.24721913])

In [149]:
np.std(arr,axis=1)

array([2.23606798, 1.47901995, 1.78535711])

# np.var()
- It returns the variance of an array.
- Variance is the square of the std

In [150]:
# np.var(arr,axis=0/1)
# arr.var(axis=0/1)

In [151]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [152]:
np.var(arr)

4.305555555555556

In [154]:
arr.std()**2

4.305555555555556

In [155]:
arr.var(axis=0)

array([4.22222222, 2.66666667, 2.        , 1.55555556])

In [156]:
arr.var(axis=1)

array([5.    , 2.1875, 3.1875])

# np.percentile()
- It returns the specified percentile value from an array

In [165]:
# np.percentile(arr,percentile_value,axis=0/1)

In [158]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [159]:
np.percentile(arr,25)

4.75

In [160]:
# CAT- 99 percentile

In [161]:
# Maximum marks=100
# Ambika- 45 and topped the exam
# What will be the percentile value- 100

In [162]:
arr

array([[2, 4, 6, 8],
       [7, 8, 9, 5],
       [4, 6, 9, 6]])

In [166]:
np.percentile(arr,[10,25,50,75,99])

array([4.  , 4.75, 6.  , 8.  , 9.  ])

In [194]:
arr

array([[85, 40, 13, 42, 71],
       [95, 45, 78, 25, 75],
       [24, 63, 67, 82, 97]])

In [195]:
np.percentile(arr,25,axis=0)

array([54.5, 42.5, 40. , 33.5, 73. ])

# np.where()

### Case_1
- np.where(condition)

- It returns the indexes where the condition is True

In [171]:
arr=np.array([11,12,13,14,15,16,17,18,19])
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [173]:
np.where(arr<15)

(array([0, 1, 2, 3], dtype=int64),)

In [174]:
np.where(arr==arr.max())

(array([8], dtype=int64),)

In [175]:
np.where(arr%2==0)

(array([1, 3, 5, 7], dtype=int64),)

In [177]:
arr=np.array([[11,12,13],[14,15,16]])
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [178]:
np.where(arr<15)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [179]:
np.where(arr%2==0)

(array([0, 1, 1], dtype=int64), array([1, 0, 2], dtype=int64))

### Case_2
- np.where(condition,x,y)

In [180]:
# - If the condition is True then x is the result.
# - If the condition is False then y is the result

In [182]:
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [185]:
np.random.seed(45)
arr=np.random.randint(10,99,15).reshape(3,5)
arr

array([[85, 40, 13, 42, 71],
       [95, 45, 78, 25, 75],
       [24, 63, 67, 82, 97]])

In [186]:
# The values that are greater than 60 should be 1
# The values that are less than 60 should be 0

In [187]:
np.where(arr>60,1,0)

array([[1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1]])

In [188]:
# The even numbers should 2 and the odd numbers should be 1

np.where(arr%2==0,2,1)

array([[1, 2, 1, 2, 1],
       [1, 1, 2, 1, 1],
       [2, 1, 1, 2, 1]])

### Case_3
- np.where(condition,x,arr)

In [189]:
# - If the condition is True then x is the result.
# - If the condition is False then no change

In [190]:
arr

array([[85, 40, 13, 42, 71],
       [95, 45, 78, 25, 75],
       [24, 63, 67, 82, 97]])

In [192]:
# All the odd numbers should be 0

np.where(arr%2!=0,0,arr)

array([[ 0, 40,  0, 42,  0],
       [ 0,  0, 78,  0,  0],
       [24,  0,  0, 82,  0]])

In [193]:
np.where(arr%2==0,arr,0)

array([[ 0, 40,  0, 42,  0],
       [ 0,  0, 78,  0,  0],
       [24,  0,  0, 82,  0]])

### Case_4
- We can use it to cap the values