In [1]:
import numpy as np

# np.where()

### Case_4
- Capping

In [5]:
np.random.seed(65)
arr=np.random.randint(10,100,12).reshape(3,4)
arr

array([[56, 73, 50, 95],
       [81, 66, 16, 11],
       [89, 19, 36, 20]])

In [6]:
# Cap the values between 30 and 70
# Any value that is greater than 70 should be 70.
# Any value that is less than 30 should be 30.
# Rest of the values should remain the same.

In [8]:
arr2=np.where(arr>70,70,arr)
arr2

array([[56, 70, 50, 70],
       [70, 66, 16, 11],
       [70, 19, 36, 20]])

In [10]:
res_arr=np.where(arr2<30,30,arr2)
res_arr

array([[56, 70, 50, 70],
       [70, 66, 30, 30],
       [70, 30, 36, 30]])

In [12]:
np.where(arr<30,30,np.where(arr>70,70,arr))

array([[56, 70, 50, 70],
       [70, 66, 30, 30],
       [70, 30, 36, 30]])

In [11]:
# [1,2,3,4,5,6,7,8,9,10]
# [3,3,3,4,5,6,7,8,8,8]

# np.clip()
- It caps the values of an array between two values and returns a new array

In [14]:
# np.clip(arr,lower_limit,upper_limit)

In [13]:
arr

array([[56, 73, 50, 95],
       [81, 66, 16, 11],
       [89, 19, 36, 20]])

In [16]:
np.clip(arr,30,70)

array([[56, 70, 50, 70],
       [70, 66, 30, 30],
       [70, 30, 36, 30]])

# np.select()
- It is used when we want to change the values in an array on the basis of multiple condistions.

In [20]:
# np.select(condition_list,choice_list,default_value)

In [18]:
arr=np.array(['married','unmarried','single','divorced','widowed','married','single','unmarried','divorced','divorced'])
arr

array(['married', 'unmarried', 'single', 'divorced', 'widowed', 'married',
       'single', 'unmarried', 'divorced', 'divorced'], dtype='<U9')

In [19]:
# married, divorced, widowed- married
# unmarried, single- single

In [21]:
cond=[arr=='divorced',arr=='widowed',arr=='unmarried',arr=='single']
choice=['married','married','single','single']
default='married'

In [22]:
np.select(cond,choice,default=default)

array(['married', 'single', 'single', 'married', 'married', 'married',
       'single', 'single', 'married', 'married'], dtype='<U7')

In [23]:
np.where(arr=='divorced','married',np.where(arr=='widowed','married',np.where(arr=='single','single',
                                                                              np.where(arr=='unmarried','single',arr))))

array(['married', 'single', 'single', 'married', 'married', 'married',
       'single', 'single', 'married', 'married'], dtype='<U9')

# Missing values in Numpy

In [24]:
# In Nnumpy the missing values are represented by np.nan
# The datatype of np.nan is float

In [27]:
arr=np.array([np.nan,np.nan])
arr

array([nan, nan])

In [28]:
arr.dtype

dtype('float64')

In [38]:
arr=np.array([5,4,np.nan])
arr

array([ 5.,  4., nan])

In [39]:
arr.dtype

dtype('float64')

# Operations on  missing values

# np.isnan()

- It checks for the np.nan values and returns a boolean array.

In [42]:
arr=np.array([10,np.nan,20,np.nan,np.nan,30,40,50,np.nan]).reshape(3,3)
arr

array([[10., nan, 20.],
       [nan, nan, 30.],
       [40., 50., nan]])

In [43]:
np.isnan(arr)

array([[False,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [72]:
# Count of missing values

np.isnan(arr).sum()

4

In [74]:
np.array([True,False,True,False]).sum()

2

In [52]:
# Count the non-nan values

x=np.isnan(arr)==False
x.sum()

5

In [55]:
np.isnan(arr)

array([[False,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [57]:
(~np.isnan(arr)).sum()

5

In [58]:
# Fetch the indexes of the missing values

arr

array([[10., nan, 20.],
       [nan, nan, 30.],
       [40., 50., nan]])

In [78]:
np.where(np.isnan(arr))

(array([0, 1, 1, 2], dtype=int64), array([1, 0, 1, 2], dtype=int64))

In [80]:
arr[np.where(np.isnan(arr))]

array([nan, nan, nan, nan])

In [63]:
# Fetch the missing values

np.isnan(arr)

array([[False,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [64]:
arr[np.isnan(arr)]

array([nan, nan, nan, nan])

In [69]:
# Fetch the non misisng values

~np.isnan(arr)

array([[ True, False,  True],
       [False, False,  True],
       [ True,  True, False]])

In [70]:
arr[~np.isnan(arr)]

array([10., 20., 30., 40., 50.])

In [81]:
# Replacing the missing values

arr

array([[10., nan, 20.],
       [nan, nan, 30.],
       [40., 50., nan]])

In [84]:
# Replace all the null values by 0

arr[np.isnan(arr)]=0

In [85]:
arr

array([[10.,  0., 20.],
       [ 0.,  0., 30.],
       [40., 50.,  0.]])

# Array Broadcasting

- When we have arrays of different shape then Numpy matches the shape of the arrays by adding dummy rows or columns to make the element by element operation possible. This is known as array broadcasting.

In [86]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
y=np.array([2,4,6])
y

array([2, 4, 6])

In [88]:
x+y

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [89]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
y=np.array([[1,2]])
y

array([[1, 2]])

In [93]:
print(x.shape)
print(y.shape)

(2, 3)
(1, 2)


In [94]:
x*y

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [96]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
y=np.array([[1],[2],[3]])
y

array([[1],
       [2],
       [3]])

In [98]:
print(x.shape)
print(y.shape)

(3, 3)
(3, 1)


In [99]:
x*y

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [100]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
y=np.array([[1,2],[2,2],[3,4]])
y

array([[1, 2],
       [2, 2],
       [3, 4]])

In [102]:
print(x.shape)
print(y.shape)

(3, 3)
(3, 2)


In [103]:
x*y

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [104]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
x+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [108]:
lst=[[1,2,3],[4,5,6],[7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [110]:
for i in range(len(lst)):
    for j in range(len(lst[i])):
        lst[i][j]+=5

In [111]:
print(lst)

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


# Random Module

- In Numpy we have a random module that is used to simulate the arrays of random numbers.

### np.random.random()

In [117]:
# - It generates the specified number of random values.
# - A random value is in between 0 and 1
# - It returns a 1-D array

In [114]:
# create an array of 1 random value

np.random.random(1)

array([0.03205585])

In [115]:
# create an array of 10 random value

In [116]:
np.random.random(10)

array([0.64425752, 0.86392611, 0.29558031, 0.156297  , 0.17534547,
       0.37992098, 0.60462603, 0.61301083, 0.65115879, 0.43032418])

In [118]:
# Create a 3*3 array of random values

np.random.random(9).reshape(3,3)

array([[0.6839961 , 0.71290513, 0.91663181],
       [0.91196018, 0.52598783, 0.47959201],
       [0.67212679, 0.23624044, 0.5445704 ]])

### np.random.rand()

In [119]:
# np.random.rand(rows,cols)

In [120]:
# Create a 3*3 array of random values

np.random.rand(3,3)

array([[0.00844416, 0.1731045 , 0.86523325],
       [0.17723251, 0.95513748, 0.57373397],
       [0.70899482, 0.64761826, 0.93089471]])

In [136]:
# Create a 3*3*4 array of random values

np.random.rand(3,3,4)

array([[[0.10438984, 0.22311706, 0.59392238, 0.16552756],
        [0.62592375, 0.71808404, 0.63664188, 0.49846771],
        [0.86070082, 0.90543067, 0.03875584, 0.84625786]],

       [[0.72168346, 0.50803784, 0.26609657, 0.11182993],
        [0.12602587, 0.10680375, 0.92118979, 0.14956125],
        [0.63203845, 0.36859401, 0.14511732, 0.15791759]],

       [[0.71347086, 0.87744137, 0.68033812, 0.3411585 ],
        [0.93056877, 0.33961048, 0.10599457, 0.35476647],
        [0.30700413, 0.90127224, 0.21816518, 0.36932806]]])

### np.random.randint()

- It returns an array of the random int values between a range.

In [122]:
# np.random.randint(start,stop,number of values)
# Stop value is excluded

In [123]:
# Create a 3*3 array of random int values between 10 and 100

In [132]:
np.random.randint(10,100,9).reshape(3,3)

array([[43, 73, 39],
       [85, 81, 92],
       [49, 96, 83]])

### np.random.seed()

In [128]:
# - It is used to fix the random state

In [165]:
np.random.seed(15)
np.random.randint(10,100,9)

array([82, 22, 15, 10, 38, 37, 81, 85, 95])

In [ ]:
array([82, 22, 15, 10, 38, 37, 81, 85, 95])

In [166]:
from numpy.random import randint,seed

In [167]:
seed(15)
randint(10,100,9)

array([82, 22, 15, 10, 38, 37, 81, 85, 95])

In [168]:
seed(2000)
randint(10,100,9)

array([64, 82, 88, 87, 64, 38, 38, 60, 65])

In [172]:
randint(10,100,9)

array([85, 96, 91, 89, 38, 68, 46, 69, 56])

In [173]:
seed(2000)

In [174]:
randint(10,100,9)

array([64, 82, 88, 87, 64, 38, 38, 60, 65])

In [175]:
# random state is from 0 to 2**32-1

In [178]:
seed(2**32)

ValueError: Seed must be between 0 and 2**32 - 1

In [177]:
2**32-1

4294967295

In [179]:
# Libraries (Numpy, Pandas-3, Matplotlib-1, Seaborn-1)
# Iterators and Generators-1
# File Handling-1

In [180]:
# Statistics -> Machine Learning Algorithms 
# Supervised
# Unsupervised- Deep Learning - NLP, Image Classification